name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # Queues.Abstractions

    - name: Restore Queues.Abstractions
      run: dotnet restore ./src/*/Queues.Abstractions.csproj

    - name: Build Queues.Abstractions
      run: dotnet build ./src/*/Queues.Abstractions.csproj --no-restore  -c Release

    - name: Pack Queues.Abstractions
      run: dotnet pack ./src/*/Queues.Abstractions.csproj --no-restore -o ~/nuget  -c Release

    # Queues.Storage

    - name: Restore Queues.Storage
      run: dotnet restore ./src/*/Queues.Storage.csproj

    - name: Build Queues.Storage
      run: dotnet build ./src/*/Queues.Storage.csproj --no-restore  -c Release

    - name: Pack Queues.Storage
      run: dotnet pack ./src/*/Queues.Storage.csproj --no-restore -o ~/nuget  -c Release

    # Queues.ServiceBus

    - name: Restore Queues.ServiceBus
      run: dotnet restore ./src/*/Queues.ServiceBus.csproj

    - name: Build Queues.ServiceBus
      run: dotnet build ./src/*/Queues.ServiceBus.csproj --no-restore  -c Release

    - name: Pack Queues.ServiceBus
      run: dotnet pack ./src/*/Queues.ServiceBus.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
