name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

    # WebJobs.Storage.Queues.Abstractions

    - name: Restore WebJobs.Storage.Queues.Abstractions
      run: dotnet restore ./src/*/WebJobs.Storage.Queues.Abstractions.csproj

    - name: Build WebJobs.Storage.Queues.Abstractions
      run: dotnet build ./src/*/WebJobs.Storage.Queues.Abstractions.csproj --no-restore  -c Release

    - name: Pack WebJobs.Storage.Queues.Abstractions
      run: dotnet pack ./src/*/WebJobs.Storage.Queues.Abstractions.csproj --no-restore -o ~/nuget  -c Release

    # WebJobs.Storage.Queues

    - name: Restore WebJobs.Storage.Queues
      run: dotnet restore ./src/*/WebJobs.Storage.Queues.csproj

    - name: Build WebJobs.Storage.Queues
      run: dotnet build ./src/*/WebJobs.Storage.Queues.csproj --no-restore  -c Release

    - name: Pack WebJobs.Storage.Queues
      run: dotnet pack ./src/*/WebJobs.Storage.Queues.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -k ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --skip-duplicate
